package com.roboquito.email.model;

public enum ServerMethods {
	
	SAVE_OBJECT, GET_ALL_OBJECTS, GET_OBJECTS_BYADDRESSEE, DELETE_OBJECT, DELETE_OBJECT_BY_DESTINATARIO,
	AUTENTICAR_USUARIO, PUBLICAR_CHAVE, GET_PUBLIC_KEY

}
